module.exports = {
    USER_CONNECTED: 'USER_CONNECTED',
    MESSAGE_SENT: 'MESSAGE_SENT',
    MESSAGE_RECIEVED: 'MESSAGE_RECIEVED',
    USER_TYPING: 'USER_TYPING',
    USER_DISCONNECTED: 'USER_DISCONNECTED',
    LOGOUT: 'LOGOUT',
    VERIFY_USER: 'VERIFY_USER',
    GET_CONNECTED_USERS: 'GET_CONNECTED_USERS'

}